apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | default "monitoring" }}
  labels:
    app.kubernetes.io/name: monitoring-stack
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}